title: The 3rd Workshop on Data Privacy and Data Analysis in Healthcare Systems
description: In conjunction with the 2026 IEEE International Conference on Healthcare Informatics (IEEE ICHI 2026) <br> 1st - 4th June 2026 - Minneapolis, MN - USA
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
sass:
  style: compressed
  load_paths:
    - _sass
  sass_dir: _sass